spring:
  application:
    name: app
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:postgresql://${APP_DATASOURCE_HOST:postgres}:${APP_DATASOURCE_PORT:5432}/${APP_DATASOURCE_DB:app}${APP_DATASOURCE_QUERY:?sslmode=disable}}
    username: ${APP_DATASOURCE_USERNAME:app}
    password: ${APP_DATASOURCE_PASSWORD:app}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_AUTH0_ISSUER:https://example.auth0.com/}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    com.example.app: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  auth0:
    issuer: ${APP_AUTH0_ISSUER:https://example.auth0.com/}
    audience: ${APP_AUTH0_AUDIENCE:}
    domain: ${APP_AUTH0_DOMAIN:}
